return function(n)

    --[[
        an efficient way to check for primality is to test whether n is divisible by 2 or 3,
        then to check through all numbers of the form 6k±1 ≤ n.
        This is 3 times faster than testing all numbers up to √n.
        see https://en.wikipedia.org/wiki/Primality_test for details.
    ]]
    local function isPrime(n)

        if n <= 1 then return false end
        if n <= 3 then return true end
        if (n % 2 == 0) or (n % 3 == 0) then return false end

        local i = 5
        local stop = math.floor(math.sqrt(n))
        while i <= stop do
            if (n % i == 0) or (n % (i + 2) == 0) then
                return false
            end
            i = i + 6
        end
        return true
    end

    --[[
        all primes after 2 and 3 are generated by the formula 6k±1
        but not all numbers in these sequences are primes.
        We can use the sequence to generate candidates and then filter out 
        which ones are pseudo-primes using the primality test above.
    ]]
    assert(n > 0, 'n must be positive')
    if n == 1 then return 2 end
    if n == 2 then return 3 end
    local count = 2
    for k = 1, math.huge do
        local p1 = 6 * k - 1
        if isPrime(p1) then
            count = count + 1
            if count == n then return p1 end
        end
        local p2 = 6 * k + 1
        if isPrime(p2) then
            count = count + 1
            if count == n then return p2 end
        end
    end

end
